# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countNonzeroColsArma <- function(mat) {
    .Call(`_tidymsi_countNonzeroColsArma`, mat)
}

countNonzeroCols <- function(mat) {
    .Call(`_tidymsi_countNonzeroCols`, mat)
}

colMediansC <- function(x) {
    .Call(`_tidymsi_colMediansC`, x)
}

rowMeansC <- function(x) {
    .Call(`_tidymsi_rowMeansC`, x)
}

normalizeTIC <- function(dataMatrix) {
    .Call(`_tidymsi_normalizeTIC`, dataMatrix)
}

nonzeroMedianC <- function(x) {
    .Call(`_tidymsi_nonzeroMedianC`, x)
}

rowNonzeroMediansC <- function(x) {
    .Call(`_tidymsi_rowNonzeroMediansC`, x)
}

normalizeNonzeroMedian <- function(dataMatrix) {
    .Call(`_tidymsi_normalizeNonzeroMedian`, dataMatrix)
}

rowMFCsC <- function(dataMatrix, refSpec) {
    .Call(`_tidymsi_rowMFCsC`, dataMatrix, refSpec)
}

rowMFCsC_nonzero <- function(dataMatrix, refSpec) {
    .Call(`_tidymsi_rowMFCsC_nonzero`, dataMatrix, refSpec)
}

normalizeMFC_nonzero <- function(dataMatrix, refSpec) {
    .Call(`_tidymsi_normalizeMFC_nonzero`, dataMatrix, refSpec)
}

intersampleNormTIC <- function(dataNormPixel, sampleFirstIndices) {
    .Call(`_tidymsi_intersampleNormTIC`, dataNormPixel, sampleFirstIndices)
}

intersampleNormMedian <- function(dataNormPixel, sampleFirstIndices) {
    .Call(`_tidymsi_intersampleNormMedian`, dataNormPixel, sampleFirstIndices)
}

intersampleNormMFC <- function(x, sampleFirstIndices) {
    .Call(`_tidymsi_intersampleNormMFC`, x, sampleFirstIndices)
}

rcpparma_hello_world <- function() {
    .Call(`_tidymsi_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_tidymsi_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_tidymsi_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_tidymsi_rcpparma_bothproducts`, x)
}

#' Blah
#' 
#' This function is a default
#'
#' @param x A vector
#' @export
rcpparma_myfun <- function(x) {
    .Call(`_tidymsi_rcpparma_myfun`, x)
}

mychar <- function(x) {
    .Call(`_tidymsi_mychar`, x)
}

